version: "3.5"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: testnode
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
